spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;INIT=RUNSCRIPT FROM 'src/main/resources/sql/init.sql';MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate