drop table if exists algo_data;

-- extract 'signals' data into database to keep code clean
create table algo_data
(
    id       int4 generated by default as identity,
    sequence varchar(255),
    primary key (id)
);

-- signal is stored as a list of key value pairs
-- key -> signal step
-- value -> parameters
insert INTO algo_data (id, sequence)
VALUES (1, '{
  "setUp": [],
  "setAlgoParam": [1, 60],
  "performCalc": [],
  "submitToMarket": []
}'),
       (2, '{
  "reverse": [],
  "setAlgoParam": [1, 80],
  "submitToMarket": []
}'),
       (3, '{
  "setAlgoParam": [1,90],
  "setAlgoParam": [2,15],
  "performCalc": [],
  "submitToMarket": []
}');
